version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: kcheranev/circleci-demo
    docker:
      - image: circleci/openjdk:8-jdk
jobs:
  compile-and-test:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle test

  build-docker-image:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: gradle final -Prelease.scope=minor
      - run: gradle clean build docker -PimageName=$IMAGE_NAME
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar

  publish-docker-image:
    executor: docker-publisher
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run: git fetch
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            echo 'tag = ' $CIRCLE_TAG
            IMAGE_TAG=${CIRCLE_TAG/v/''}
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$IMAGE_TAG

workflows:
  version: 2
  build-master:
    jobs:
      - compile-and-test
      - build-docker-image:
          requires:
            - compile-and-test
          filters:
            branches:
              only: master
      - publish-docker-image:
          requires:
            - build-docker-image
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/